sudo: false
language: elixir
elixir:
  - 1.12
otp_release:
  - 24.0
cache:
  directories:
    - _build
    - deps
env:
  global:
    - HEX_USERNAME=jwietelmann
install:
  - gem install coveralls-multi --no-document
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.json
  - coveralls-multi
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  # https://docs.travis-ci.com/user/deployment/script/
  # > `script` must be a scalar pointing to an executable file or command.
  provider: script
  # http://yaml.org/spec/1.2/spec.html#id2779048
  # `>-` indicates the line folding.
  script: mix hex.publish --yes
  on:
    tags: true
